### ISSUE TITLE
F4CKFixes 1.8 release

### ISSUE THREAD

**Issue by Perchik71** [Perchik71/Fallout4Test#10]
At the request of workers previs.
So as not to forget:

- [x] Use the memory manager from 1.6.
- [x] Enable the processing of names with spaces in the commands -BuildCDX, -CompressPSG.
- [x] Migrate from 1.7 IOPatch and enable synchronization to increase speed.
- [x] It seems that when working from the console, you can safely allow working with files larger than 4GB.
- [x] Migrate from 1.7 UIHotkeys, RefLinkGeometryHangWorkaround, VersionControlMergeWorkaround, AttachRenderWindow, DisableAssertions.
- [x] Remove option SkipAnimationBuildProcessData, CheckVTable.
- [x] Modify the Log window.
- [x] Color markup of plugins to Data window.
- [x] Compression of the dump and the log file to the archive.

**Comment by feeddanoob** [comment]
Thank you for continuing the CK fixes builds, I thought 1.7 would be the final release. Also Idk who told you about the buildCDX or CompressPSG commands not being able to process esp names with spaces, but thank you for looking into this.
