### ISSUE TITLE
[Feature Request] Allow the Creation Kit to accept quotation marks in command-line

### ISSUE THREAD

**Issue by Sauron462** [Perchik71/Fallout4Test#4]
Hello Perchik71, I have a small feature I would like to request. 
To further explain what I mean in the title is that the Creaton Kit through command-line doesn't work with plugins that have a space in their name, I've had a few issues with removing the spaces and restoring them, and the Creation Kit doesn't seem to accept enclosing plugin names in quotations.
I have very little experience coding, so for the time being I'm just going to hope asking you would work.
I understand if you don't want/don't have time to do so.

**Comment by Perchik71** [comment]
Yes, CK64 does not support this, because it uses strtok, which separates everything up to the first match, there is a space there.
I only found a couple of places in the debugger, I would like to get a list of commands or where to find them to find places in the code. Then can start looking for a solution to the problem.

**Comment by Sauron462** [comment]
I believe this is everything, however I should do some more research (was traveling):
```
-OptimizeMasterFile
-ExportDialogue
-GenerateLips
-ExportFaceGenData
-TagifyMasterfile
-ExportText
-CompileTextExport
-DelocalizeMasterfile
-SaveDefaultPlugin
-CheckInPlugin
-DumpNeededFiles
-OptimizeDLC
-GenerateSEQ
-GenerateWarnings
-GenerateAnimInfo
-GenerateSingleLip
-GenerateStaticCollections
-GeneratePreCombined
-GeneratePreVisData
-DepersistRefs
-MapMaker
-MapInfo
-OutputAreaArt
-UpdateModelData
-ExportDismemberData
-ConvertMaterials
-ImportScalingData
-CompressPSG
-BuildCDX
-ConvertToESL
```

**Comment by Perchik71** [comment]
Not all commands are present in the code, but I fixed the ones that are there. All changes with comments in the file Editor.cpp.
