### ISSUE TITLE
Build fix.

### ISSUE THREAD

**Issue by Diskmaster** [Perchik71/Fallout4Test#9]
https://github.com/Perchik71/Fallout4Test/blob/d8f3a0f708a46c9be298b019a23641d87ccaf8c6/%5BCommon%5D/CommInc.h#L70

The above appears to be busted due to a codepage change. The code expects Config.h. The file should probably be resaved in unicode after fixing the minor error. If git still thinks it's a local codepage, there's probably something wrong with an .gitattribute assignment or something that's out of my realm of expertise.

Also, I get ```C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\um\winnt.h(2513,40): error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined. (compiling source file [EditorAPI]\BGSLayer.cpp)``` during compile. I can get around this with the option set, but that might not be intended.

**Comment by Perchik71** [comment]
No, this is an annoying mistake caused by the fact that English C and Russian C are the same keys.
I'll fix it of course. WINDOWS_IGNORE_PACKING_MISMATCH is an error from the new SDK from Microsoft, I'm sticking with the Win10 SDK for now.
